### ISSUE TITLE
Roman numerals when viewing School of Malignancies in culture tab aren't formatted correctly? It's shown as "Death_coloring II" when I'm guessing it should just be the II

### ISSUE THREAD

**Issue by MaxxxEC** [ThePinkPanzer/Godherja-Github-Version#578]
https://imgur.com/a/eTHqqkw

**Comment by MaxxxEC** [comment]
https://imgur.com/a/uA3PYTH
Also found it in the magic screen

**Comment by debnet** [comment]
Full Barbershop integration is the culprit: it overrides localization string for "death", adding a upper case and messing with magic aspect.

`localization\english\big_barber_l_english.yml`

```yml
l_english:
 #for Fate of Iberia
 iberian_bgs: "Iberian"
 muslim: "Muslim"
 christian: "Christian"
 chess_certain_win_barber_name: "Chess winning"
 chess_cocky_barber_name: "Chess thinking"
 death: "Death"  # To remove or change to "death"
 ...
```
